### ISSUE TITLE
На next 13 не работает твоя сборка next + eslint + prettier

### ISSUE THREAD

**Issue by easy-why-not** [debabin/react-poketinder#1]
<img width="1960" alt="Снимок экрана 2022-12-08 в 11 49 13" src="https://user-images.githubusercontent.com/68082092/206401075-1ecb8fb4-32bb-4cc7-b2d9-0bef0ea5bd38.png">
Я скопировал у тебя все настройки, зависимости и конфиги - вот такая ошибка падает

**Comment by easy-why-not** [comment]
Причем parser.options указан:
 overrides: [
        {
            files: ['*.ts', '*.tsx'],
            parserOptions: {
                project: ['./tsconfig.json']
            }
        }
    ],

**Comment by debabin** [comment]
Привет, вообще приложение же делалось на 12 версии. Точно ли проблема в 13 версии next, если да то нужно смотреть.

**Comment by debabin** [comment]
@easy-why-not можешь скинуть скрины eslint prettier и tsconfig, теперь понял проблему. Странно, ведь еслинт и тс ни как не привязаны к next13.

**Comment by easy-why-not** [comment]
Все конфиги у тебя скопипастил. Уже переустановил на то, что некст предлагает

**Comment by debabin** [comment]
@easy-why-not короче, я глянул в чем проблема. На самом деле это ошибка не ломает lint команду и все отлично работает (если ты используешь typescript only). Проблема вот тут описана неплохо [тут](https://stackoverflow.com/questions/58510287/parseroptions-project-has-been-set-for-typescript-eslint-parser).

Можно

- описать парсер для js файлов (просто у меня был там только ts)
- добавить все js файлы в исключения 

Ну первый вариант, конечно же правильный

**Comment by debabin** [comment]
Хочу сейчас попробовать настроить, но вот такое самое просто решение [туть](https://bobbyhadz.com/blog/typescript-parseroptions-project-has-been-set-for) @easy-why-not

**Comment by debabin** [comment]
Ну если вкратце я еще поресерчил, @easy-why-not вот тут [топик](https://github.com/iamturns/eslint-config-airbnb-typescript/issues/96) на нашу тему. 

Если вкратце, пофиг на js файлы если ты ставишь typescript parser.

@easy-why-not  вот довольно не плохое [решение](https://github.com/iamturns/eslint-config-airbnb-typescript/issues/110)

**Comment by debabin** [comment]
@easy-why-not закрываем ?

**Comment by easy-why-not** [comment]
> @easy-why-not закрываем ? 

Угу. Спасибо, друг

**Comment by easy-why-not** [comment]
Ох прости. Решил, все таки, попробовать настроить нормально. 
Взял решение из этого топика: https://github.com/iamturns/eslint-config-airbnb-typescript/issues/110#issuecomment-646942818
те добавил "**/*.js" в    `"include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", "**/*.js"],`
```
Parsing error: ESLint was configured to run on `<tsconfigRootDir>/.eslintrc.js` using `parserOptions.project`: <tsconfigRootDir>/../../../../users/aleksandrnistratov/desktop/12/tsconfig.json
However, that TSConfig does not include this file. Either:
- Change ESLint's list of included files to not include this file
- Change that TSConfig to include this file
- Create a new TSConfig that includes this file and include it in your parserOptions.project
See the typescript-eslint docs for more info: https://typescript-eslint.io/linting/troubleshooting##i-get-errors-telling-me-eslint-was-configured-to-run--however-that-tsconfig-does-not--none-of-those-tsconfigs-include-this-file
```
    Не понимаю(

**Comment by easy-why-not** [comment]
Тут прост понимаешь в чем главный трабл. Так т можно забить на эту ошибку, но я поставил прекоммит хук, который пускает проверки eslint, prettier, stylelint перед коммитом - падает ошибка = не коммитит

**Comment by easy-why-not** [comment]
Удалось порешать, но мне не нравится. Добавил в конфиг еслинта - ignorePatterns: ['/*.js'],
